### ISSUE TITLE
Example of how to initialise a new shape and pass in the callbacks for `getPointCount()` and `getPoint()`?

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#11]
Hello,

I am creating my own OOP wrappers around these bindings, and I have created a `Shape` class.

I want to create a pointer to an `sf_shape` object and pass in the callback function to the subclass's `getPointCount()` and `getPoint()` functions:

```D
this() {
    sfShapeGetPointCountCallback callback1 = &getPointCount;
    sfShapeGetPointCallback callback2 = &getPoint;
    ptr = sfShape_create(callback1, callback2, null);
}

private static ulong getPointCount(void* data) {

}

private static sfVector2f getPoint(size_t index, void* data)  {

}
```

The code above isn't working, which is weird.

I am getting the following warning:

```
cannot implicitly convert expression `& getPointCount` of type `ulong function(void* data)` to `extern (C) ulong function(void*) nothrow
```

I am unsure how to go around this, the compiler is warning me to add `extern(C)` and `nothrow` modifications. I understand the `extern(C)` but the `nothrow` will ruin the code.

**Most of my child functions are not `nothrow`** so this modification to the function would make it **impossible to call my class's functions.** Please change this in your library or maybe I am understand this wrong, I think you should be providing a non-`throw` way of doing callbacks.

I am unsure what to do/how to go around this, it'd be great to see an example of how you guys would use these functions.

Any help with this would be greatly appreciated.

Regards,
thebluepandabear

**Comment by ichordev** [comment]
That is not a warning, it’s an error because you’ve given the function the wrong type. The error message tells you exactly what’s wrong here: The function pointers provided to `sfShape_create` must point to functions that are marked as `nothrow` and `extern(C)`. There are a lot of reasons for this, like C code not knowing how to handle errors thrown in D code. If you don’t know what nothrow and extern(C) are then I’d advise you look up some tutorials and in particular the D specification to get more familiar with D's function attributes and what they do. If you truly insist on using extern(D) and throwing exceptions that C won’t be able to handle in these functions then you could cast the function pointer, but you will almost certainly cause serious issues this way and should never do so in production code.

**Comment by therealbluepandabear** [comment]
k my bad

**Comment by therealbluepandabear** [comment]
When you have free time could you show me an example of drawing a custom shape? Such as a simple polygon? Thanks.

**Comment by ichordev** [comment]
Issues are primarily to report bugs.
If you want a more immediate answer than on SO you could post in the help section of a D language community.
