### ISSUE TITLE
Upgrade to 2.5.1 

### ISSUE THREAD

**Issue by therealbluepandabear** [BindBC/bindbc-sfml#5]
I was wondering whether you are planning to update these bindings to use SFML 2.5.1?

**Comment by ichordev** [comment]
Great question! From looking at the changelog, 2.5.1 is a patch release (this is usually what the third digit of a version number is used for), which means that it contains bugfixes but importantly *no API changes*. Because of this, you should absolutely be able to use SFML 2.5.1 with bindbc-sfml configured for 2.5.0. Since there are no API changes, there's not really anything that can be done to the bindings for them use SFML 2.5.*1* since all the symbols are probably exactly the same.
